### ISSUE TITLE
Screen size?

### ISSUE THREAD

**Issue by wcmedic** [hymnis/docker-irssi#1]
I got this to work perfectly thank you!  Is there a way to change the screen terminal size to 110x80 by default using your image?

**Comment by hymnis** [comment]
Glad you got it working for you.

One way is to adjust your terminal to the size you want and make sure that `screen` fits (ctrl- a + F). It's also possible to set width and height for `screen` and supply your own `.screenrc` file with custom settings. Simply mount your rc file to `/home/user/.screenrc` to use your own settings.

**Comment by wcmedic** [comment]
I actually did figure it out... In portainer I edited the container and in ENV tab I added two one for columns and one for lines.

Columns = 110
Lines = 24

Worked like a charm, just an fyi incase someone else were to ask you...

Thank you for your work..

**Comment by hymnis** [comment]
Nice! Thank you for taking the time to share the solution.
